### ISSUE TITLE
helmit cannot run consecutive suite tests 

### ISSUE THREAD

**Issue by adibrastegarnia** [onosproject/helmit#26]
Just run onos-config integrations tests:
```
helmit test ./cmd/onos-config-tests -c ../onos-helm-charts
```

And you will get this error after cli tests are finished and gnmi tests started. 

```
2020/08/07 21:34:12 CRD databases.cloud.atomix.io is already present. Skipping.
2020/08/07 21:34:12 creating 1 resource(s)
2020/08/07 21:34:12 CRD members.cloud.atomix.io is already present. Skipping.
2020/08/07 21:34:12 creating 1 resource(s)
2020/08/07 21:34:12 CRD partitions.cloud.atomix.io is already present. Skipping.
2020/08/07 21:34:12 creating 1 resource(s)
2020/08/07 21:34:12 CRD primitives.cloud.atomix.io is already present. Skipping.
2020/08/07 21:34:12 Clearing discovery cache
2020/08/07 21:34:12 beginning wait for 0 resources with timeout of 1m0s
    gnmi: test.go:65: test panicked: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: default, name: onos-config-atomix-kubernetes-controller, existing_kind: /v1, Kind=ServiceAccount, new_kind: /v1, Kind=ServiceAccount
        goroutine 11 [running]:
        runtime/debug.Stack(0xc00021bcd8, 0x1e3eb80, 0xc000fff8a0)
        	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
        github.com/onosproject/helmit/pkg/test.failTestOnPanic(0xc0002c2c60)
        	/Users/adibrastegarnia/go/pkg/mod/github.com/onosproject/helmit@v0.6.6/pkg/test/test.go:65 +0x57
        panic(0x1e3eb80, 0xc000fff8a0)
        	/usr/local/go/src/runtime/panic.go:975 +0x3e3
        github.com/onosproject/helmit/pkg/test.RunTests(0xc0002c2c60, 0x1fa7120, 0x34d8580, 0x0, 0x0, 0x0)
        	/Users/adibrastegarnia/go/pkg/mod/github.com/onosproject/helmit@v0.6.6/pkg/test/test.go:91 +0x5ad
        github.com/onosproject/helmit/pkg/test.(*Worker).runTests.func1(0xc0002c2c60)
        	/Users/adibrastegarnia/go/pkg/mod/github.com/onosproject/helmit@v0.6.6/pkg/test/worker.go:77 +0x5c
        testing.tRunner(0xc0002c2c60, 0xc000293c20)
        	/usr/local/go/src/testing/testing.go:991 +0xdc
        created by testing.(*T).Run
        	/usr/local/go/src/testing/testing.go:1042 +0x357
--- FAIL: gnmi (6.77s)
```

**Comment by adibrastegarnia** [comment]
resolved
